### ISSUE TITLE
No warning when returning undefined variable

### ISSUE THREAD

**Issue by slifin** [TysonAndre/PhanUnusedVariable#6]
I don't appear to be getting a warning in this circumstance: 

```php
(function () {
  return $trolol;
})();
```

**Comment by TysonAndre** [comment]
This plugin is for catching **unused** variables, not for catching **undefined** variables.

Catching undeclared variables is already done by Phan itself.

```
src/undef.php:3 PhanUndeclaredVariable Variable $trolol is undeclared
```
